#!/bin/bash


banner() {
clear
echo -e "${white} +-----------------------------------------+"
echo -e "${white} |  ${green}████████╗ ██████╗ ███╗   ██╗██╗   ██╗  ${white}|"
echo -e "${white} |  ${green}╚══██╔══╝██╔═══██╗████╗  ██║╚██╗ ██╔╝  ${white}|"
echo -e "${white} |  ${green}   ██║   ██║   ██║██╔██╗ ██║ ╚████╔╝   ${white}|"
echo -e "${white} |  ${green}   ██║   ██║   ██║██║╚██╗██║  ╚██╔╝    ${white}|"
echo -e "${white} |  ${green}   ██║   ╚██████╔╝██║ ╚████║   ██║     ${white}|"
echo -e "${white} |  ${green}   ╚═╝    ╚═════╝ ╚═╝  ╚═══╝   ╚═╝     ${white}|"
echo -e "${white} +-----------------------------------------+"
echo -e "${white} | ${green}██╗     ██╗███╗   ██╗██╗   ██╗██╗  ██╗ ${red}H${white}|"
echo -e "${white} | ${green}██║     ██║████╗  ██║██║   ██║╚██╗██╔╝ ${red}A${white}|"
echo -e "${white} | ${green}██║     ██║██╔██╗ ██║██║   ██║ ╚███╔╝  ${red}C${white}|"
echo -e "${white} | ${green}██║     ██║██║╚██╗██║██║   ██║ ██╔██╗  ${red}K${white}|"
echo -e "${white} | ${green}███████╗██║██║ ╚████║╚██████╔╝██╔╝ ██╗ ${red}E${white}|"
echo -e "${white} | ${green}╚══════╝╚═╝╚═╝  ╚═══╝ ╚═════╝ ╚═╝  ╚═╝ ${red}D${white}|"
echo -e "${white} +-----------------------------------------+"
}
banner
